export default {
  PRODUCTS_START: 'PRODUCTS_START',
  PRODUCTS_SUCCESS: 'PRODUCTS_SUCCESS',
  PRODUCTS_ERROR: 'PRODUCTS_ERROR',
  FAVORITE_ADD: 'FAVORITE_ADD',
  FAVORITE_REMOVE: 'FAVORITE_REMOVE',
};
